import type { CreatorsArray } from '@/components/interfaces/creators';

export const creators: CreatorsArray = [
  {
    avatar: '/src/shared/img/avatarkeepitreal.png',
    nickname: 'Jaydon Ekstrom Bothman',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatardigilab.png',
    nickname: 'Ruben Carder',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatargravityone.png',
    nickname: 'Alfredo Septimus',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarjuanie.png',
    nickname: 'Davis Franci',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarbluewhale.png',
    nickname: 'Livia Rosser',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarmrfox.png',
    nickname: 'Kianna Donin',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarshroomie.png',
    nickname: 'Philip Lipshutz',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarrobotica.png',
    nickname: 'Maria Rosser',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarrustyrobot.png',
    nickname: 'Kianna Stanton',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarangelubin.png',
    nickname: 'Angel Lubin',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avataralissontorff.png',
    nickname: 'Allison Torff',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatardavisworkman.png',
    nickname: 'Davis Workman',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarlindsey.png',
    nickname: 'Lindsey Lipshutz',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avataranimakid.png',
    nickname: 'Randy Carder',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatardotgu.png',
    nickname: 'Lyduia Culhane',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarraynabator.png',
    nickname: 'Rayna Bator',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarghiblier.png',
    nickname: 'Jocelyn Westervelt',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarkeepitreal.png',
    nickname: 'Marilyn Torff',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatarangelubin.png',
    nickname: 'Skylar Levin',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
  {
    avatar: '/src/shared/img/avatargravityone.png',
    nickname: 'Terry Dorwart',
    change: '+1.41%',
    sold: '602',
    volume: '12.4 ETH',
  },
];
